language: node_js

node_js:
  - "12"
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/regnum-test

before_script:
  - psql -c 'create database  regnum-test;' -U postgres
  - psql -U postgres -d regnum-test -a -f tables.sql

services:
  - postgresql