language: node_js

node_js:
  - "12"
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration-test

before_script:
  - psql -c 'create database  greet_tests;' -U postgres
  - psql -U postgres -d greet_tests -a -f tables.sql

services:
  - postgresql